---
- hosts: all
  name: Add cis-92 packages
  become: yes
  tasks:
    - name: Create an ext4 filesystem on /dev/sdb
      filesystem:
        fstype: ext4
        dev: /dev/sdb
    - name: Create the directory /data
      ansible.builtin.file:
        path: /data
        state: directory
        mode: '0755'
    - name: Mount /dev/sdb to /data
      mount:
        src: /dev/disk/by-id/google-data-disk
        path: /data
        fstype: ext4
        state: mounted